Remove branches from matrix; Push to git

diff --git a/.github/workflows/checkUpstream.yml b/.github/workflows/checkUpstream.yml
--- a/.github/workflows/checkUpstream.yml
+++ b/.github/workflows/checkUpstream.yml
@@ -27,7 +27,6 @@ jobs:
         run: |
           matrix=$(
           echo {\
-            $(.github/helperScripts/remoteBranchNamesToJSON.sh)", "\
             $(.github/helperScripts/tomcatVersions.sh)", "\
             $(.github/helperScripts/jdkVersions.sh)\
           }\
@@ -69,7 +68,7 @@ jobs:
 
     - name: Check matrix outputs
       run: |
-        echo "Branch: ${{ matrix.branch }} Tomcat: ${{ matrix.tomcat }} JDK: ${{ matrix.jdk }}"
+        echo "Tomcat: ${{ matrix.tomcat }} JDK: ${{ matrix.jdk }}"
 
     - name: Grab the most recent upstream tomcat version
       run: |
@@ -80,32 +79,20 @@ jobs:
     - name: Check if up to date
       run: |
         echo Latest upstream version: ${{ env.upstream }}
-        git branch --list -r "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk" | head -c1 | wc -c
+        git branch --list -r "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk"
         test $(git branch --list -r "origin/${{ matrix.tomcat }}.*-jdk${{ matrix.jdk }}-openjdk" | head -c1 | wc -c) -ne 0 &&
         up2date=true || up2date=false
         echo "Up to date with latest version (${{ env.upstream }})?"
         echo $up2date
         echo "up2date=$up2date" >> $GITHUB_ENV
 
-    #- name: Does most recent version exist
-    #  run: |
-    #    echo ${{ env.upstream }}
-    #    git branch -a
-    #    git branch -a | grep "${{ env.upstream }}" &&
-    #    echo "Already up to date with Tomcat ${{ env.upstream }}" ||
-    #    {
-    #    echo "New Tomcat version ${{ env.upstream }}"
-    #    git branch -r | ${{ scriptsdir }}/findTomcatVersion.sh ${{ matrix.tomcat }} ${{ matrix.jdk }} 
-    #    echo "Psuedocode: Find most up to date tomcat version ${{ matrix.tomcat }} with jdk version ${{ matrix.jdk }}" &&
-    #    echo "Psuedocode: Branch off of most recent version in repo"
-
     - name: Already up to date
-      if: ${{ env.up2date == true}}
+      if: ${{ env.up2date == 'true'}}
       run: |
         echo "Already up to date with upstream: ${{ env.upstream }}"
 
     - name: Checkout branch
-      if: ${{ env.up2date != true }}
+      if: ${{ env.up2date != 'true' }}
       run: |
         echo "tag=${{ env.upstream }}" >> $GITHUB_ENV
         echo "New upstream version ${{ env.upstream }}"
@@ -121,5 +108,20 @@ jobs:
         sed -e "s/FROM tomcat:.*/FROM tomcat:${{ env.upstream }}/g" Dockerfile -i
         grep "FROM tomcat:" Dockerfile
 
-    - name: Commit and push changes
-      run: echo "Commit and push changes"
+    - name: Push to git
+      if: ${{ env.up2date != 'true' }}
+      run: |
+        git config --global user.name 'Github Actions'
+        git config --global user.email 'respinoza@ucar.edu'
+        git add . && git commit -m "Update to tomcat:${{ env.upstream }}" && \
+        git push origin ${{ env.upstream }}
+
+    - name: Push to dockerhub
+      if: ${{ env.up2date != 'true' }}
+      run: |
+        exit 0
+        docker logout
+        echo ${{ secrets.registrypwd }} | docker login -u ${{ secrets.registryuser }} --password-stdin
+        docker push ${{ secrets.imagename }}:${{ env.tag }} && \
+        { docker logout && echo "Successfully pushed ${{ secrets.imagename }}:${{ env.tag }}"; } ||
+        { docker logout && echo "Docker push failed" && exit 1; }
